config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index', as: 'root'

  resources :departments do
    resources :plans
  end

  get 'plans/:id/pdf', to: 'plans#export_as_pdf', as: 'plan_pdf'

  resources :plans do
    resources :flow_steps
  end

  resources :flow_steps do
    resources :tasks
  end

  resources :tasks

  resources :tasks do
    resources :task_states
    resources :comments
  end

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resources :users
end

app/views/layouts/parts/_comments_block.html.haml
.row.d-flex.justify-content-center.mt-100.mb-100
  .col-lg-6
    .card
      .card-body.text-center
        %h4.card-title Comments
      .comment-widgets
      - comments.each do |c|
        .d-flex.flex-row.comment-row.m-t-0
          .p-2
            = image_tag((c.user.avatar), class: 'rounded-circle', alt: 'Avatar', :width => "50") if c.user.avatar.attached?
          .comment-text.w-100
            %h6.font-medium
              =c.user.first_name
            %span.m-b-15.d-block
              =c.body
            %hr/

app/views/layouts/parts/_flash.html.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/parts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  = link_to 'Home', root_path, class: 'navbar-brand'
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        = link_to 'Departments', departments_path, class: 'nav-link'
      %li.nav-item.active
        = link_to 'Users', users_path, class: 'nav-link'
      - if user_signed_in?&&current_user.admin?
        %li.nav-item.active.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
            Admin
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            = link_to 'Add dep', new_department_path, class: 'dropdown-item'
            = link_to 'Invite user', new_user_invitation_path, class: 'dropdown-item'
            -#.dropdown-divider
            -#%a.dropdown-item{:href => "#"} Something else here
      - if user_signed_in?
        %li.nav-item.active
          = link_to 'Edit myself', '/users/edit', class: 'nav-link'
        %li.nav-item.active
          = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        %li.nav-item.active
          = link_to 'Sign in', new_user_session_path, class: 'nav-link'