config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index', as: 'root'

  resources :departments do
    resources :plans
  end

  get 'plans/:id/pdf', to: 'plans#export_as_pdf', as: 'plan_pdf'

  resources :plans do
    resources :flow_steps
  end

  resources :flow_steps do
    resources :tasks
  end

  resources :tasks

  resources :tasks do
    resources :task_states
    resources :comments
  end

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resources :users
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :flow_step
  has_many :comments, as: :commentable
  has_many :task_states, dependent: :destroy

  has_rich_text :description

  enum level: User.levels
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :authorize_record
  before_action :find_task, only: %i[edit update show destroy]

  def new
    @flow_step = FlowStep.new
  end

  def create
    @flow_step = FlowStep.find(params[:flow_step_id])

    if @flow_step.tasks.create(task_params)
      redirect_to @flow_step.plan
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    if @task.update(task_params)
      redirect_to @task.flow_step.plan
    else
      render 'edit'
    end
  end

  def show
    if (@state = TaskState.where(user_id: current_user.id, task_id: @task.id).first)
      @state
    else
      @state = TaskState.create(user_id: current_user.id, task_id: @task.id)
    end
    @comment = Comment.new
  end

  def destroy
    redirect_to @task.flow_step.plan
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :level, :flow_step_id, :plan_id)
  end

  def authorize_record
    authorize Task
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/views/tasks/edit.html.haml
%h3 Editing
= form_with model: @task, url: task_path, method: :put do |f|
  .field
    = f.label :label
    = f.text_field(:title, class: 'form-control')
  .field
    = f.label :description
    = f.rich_text_area(:description)
  .field
    = f.label :flow_step_id
    = f.select :flow_step_id, @task.flow_step.plan.flow_steps.collect { |flow| [flow.title, flow.id]}, {}, {class: 'form-control'}
  .field
    = f.label :level
    = f.select :level, User.levels.keys, {}, {class: 'form-control'}
  .actions
    %br/
    = f.submit(class: 'btn btn-success')
.outer
  .inner
    = button_to 'Delete Task', task_path(@task), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger'
  .inner
    = link_to 'Show mode', task_path(@task), :class => 'btn btn-primary'

app/views/tasks/new.html.haml
= form_for(:task, url: department_plan_flow_step_tasks_path(@flow_step)) do |f|
  %p
    = f.label(:title)
    = f.text_field(:title, {:class => 'form-control'})
  %p
    = f.label(:description)
    = f.text_field(:description, {:class => 'form-control'})
  %p
    = f.submit("Add task", {:class => 'btn btn-success'})

app/views/tasks/show.html.haml
%h3= @task.title
= @task.description
= form_with model: @state, url: task_task_state_path(id: @state.id, task_id: @task.id), method: :put do |f|
  .field
    %br
    = f.select :state, TaskState.states.keys, {}, {class: 'form-control'}
  .actions
    %br
    = f.submit("Save", class: 'btn btn-success')

= form_for(:comment, url: task_comments_path(@task), method: :post) do |f|
  .field
    = f.text_field(:body, {:class => 'form-control'})
  .actions
    %br/
    = f.submit("Add comment", {:class => 'btn btn-success'})


= render partial: 'layouts/parts/comments_block', locals: { comments: @task.comments }