config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index', as: 'root'

  resources :departments do
    resources :plans
  end

  get 'plans/:id/pdf', to: 'plans#export_as_pdf', as: 'plan_pdf'

  resources :plans do
    resources :flow_steps
  end

  resources :flow_steps do
    resources :tasks
  end

  resources :tasks

  resources :tasks do
    resources :task_states
    resources :comments
  end

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resources :users
end

app/models/department.rb
# frozen_string_literal: true

class Department < ApplicationRecord
  include SharedScopes
  has_many :users
  has_many :plans, dependent: :destroy

  has_one_attached :cover_img

  scope :search_by_title, ->(title) { where('(title like ?) OR title in (?)', "%#{title}%", title.split) }
end

app/controllers/departments_controller.rb
# frozen_string_literal: true

class DepartmentsController < ApplicationController
  before_action :authorize_record, except: [:destroy]
  before_action :find_dep, only: %i[show edit update destroy]

  def show
  end

  def index
    @departments = Department.all
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(dep_params)

    if @department.save
      redirect_to @department
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @department.update(dep_params)
      redirect_to @department
    else
      render 'edit'
    end
  end

  def destroy
    authorize @department
    @department.destroy
    redirect_to departments_path
  end

  private

  def dep_params
    params.require(:department).permit(:title, :cover_img)
  end

  def authorize_record
    authorize Department
  end

  def find_dep
    @department = Department.find(params[:id])
  end
end

app/views/departments/edit.html.haml
%h3 Editing
= form_for :department, url: department_path(@department), method: :put do |f|
  %p
    First name
    %br/
    = f.text_field(:title, class: 'form-control')
  %p
    Cover img
    %br/
    = f.file_field(:cover_img)
  %p
    = f.submit(class: 'btn btn-success')

app/views/departments/index.html.haml
- @departments.each do |dep|
  .card{:style => "width: 18rem;"}
    = image_tag(dep.cover_img, class: 'card-img-top', alt: 'Cover img') if dep.cover_img.attached?
    .card-body{:style => 'text-align: center;'}
      %h5.card-title
        = dep.title
      .outer
        %div.inner
          = link_to 'Open', department_path(dep), :class => 'btn btn-primary'
        %div.inner
          = button_to 'Delete', department_path(dep), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger'
        %div.inner
          = link_to 'Edit', edit_department_path(dep), :class => 'btn btn-warning'

app/views/departments/new.html.haml
= form_for :department, url: departments_path do |f|
  %p
    Title
    %br/
    = f.text_field(:title, class: 'form-control')
  %p
    Cover img
    %br/
    = f.file_field(:cover_img)
  %p
    = f.submit(class: 'btn btn-success')

app/views/departments/show.html.haml
%div{:style => "text-align: center;"}
  %h2= @department.title
  = link_to 'Add plan', new_department_plan_path(@department.id), class: 'btn btn-primary'

- @department.plans.each do |plan|
  .alert.alert-light{:style => "text-align: center;"}
    %strong= plan.title
    .outer
      .inner
        = link_to 'Open', department_plan_path(id: plan.id, department_id: @department.id), :class => 'btn btn-primary'
      .inner
        = button_to 'Delete', department_plan_path(id: plan.id, department_id: @department.id), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger'
      .inner
        = link_to 'Edit', edit_department_plan_path(id: plan.id, department_id: @department.id), :class => 'btn btn-warning'