config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index', as: 'root'

  resources :departments do
    resources :plans
  end

  get 'plans/:id/pdf', to: 'plans#export_as_pdf', as: 'plan_pdf'

  resources :plans do
    resources :flow_steps
  end

  resources :flow_steps do
    resources :tasks
  end

  resources :tasks

  resources :tasks do
    resources :task_states
    resources :comments
  end

  devise_for :users, controllers: { invitations: 'users/invitations' }

  resources :users
end

app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  belongs_to :department
  has_many :flow_steps, dependent: :destroy
end

app/controllers/plans_controller.rb
# frozen_string_literal: true
class PlansController < ApplicationController
  before_action :authorize_record
  before_action :find_plan, only: %i[show edit update destroy export_as_pdf]

  def show

  end

  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @department = Department.find(params[:department_id])

    if (@plan = @department.plans.create(plan_params))
      redirect_to @department
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @plan.update(plan_params)
      redirect_to @plan
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to @plan.department
    @plan.destroy
  end

  def export_as_pdf
    ExportPlanJob.perform_later(current_user.email, @plan)
    redirect_to @plan
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :department_id)
  end

  def authorize_record
    authorize Plan
  end

  def find_plan
    @plan = Plan.find(params[:id])
  end
end

app/views/plans/_show.html.haml
%div{:style => "text-align: center;"}
  %h2= @plan.title
  -if current_user.admin?
    = form_for(:flow_step, url: plan_flow_steps_path(plan_id: @plan.id)) do |f|
      %p
        = f.text_field(:title, {:class => 'form-control'})
      %p
        = f.submit("Add flow step", {:class => 'btn btn-success'})
        = link_to "Get PDF to email", plan_pdf_path(@plan), class: "btn btn-primary", data: {confirm: "Are you sure?"}
#plan
  %section.lists-container
    - @plan.flow_steps.each do |fs|
      .list
        %h3.list-title= fs.title
        %ul.list-items
          - fs.tasks.each do |task|
            - if current_user.admin?
              = link_to edit_task_path(task) do
                %li= task.title
            -elsif current_user.level == task.level
              = link_to task_path(task) do
                %li= task.title
      -if current_user.admin?
        = form_for(:task, url: flow_step_tasks_path(flow_step_id: fs.id, plan_id: @plan.id), method: :post) do |f|
          %p
            = f.text_field(:title, {:class => 'form-control'})
          %p
            = f.submit("Add task", {:class => 'add-card-btn btn'})

app/views/plans/edit.html.haml
%h3 Editing
= form_for :plan, url: plan_path(@plan), method: :put do |f|
  %p
    First name
    %br/
    = f.text_field(:title, class: 'form-control')
  %p
    = f.submit(class: 'btn btn-success')

app/views/plans/index.html.haml
- @plans.each do |plan|
  %div
    %h3= plan.title
    = link_to 'Open', plan_path(plan)

app/views/plans/new.html.haml
= form_for :plan, url: department_plans_path(params[:department_id]) do |f|
  %p
    Title
    %br/
    = f.text_field(:title, class: 'form-control')
  / <p>
  / Dep id <br>
  / </p>
  %p
    = f.submit(class: 'btn btn-success')

app/views/plans/show.html.haml
%div{:style => "text-align: center;"}
  %h2= @plan.title
  -if current_user.admin?
    = form_for(:flow_step, url: plan_flow_steps_path(plan_id: @plan.id)) do |f|
      %p
        = f.text_field(:title, {:class => 'form-control'})
      %p
        = f.submit("Add flow step", {:class => 'btn btn-success'})
        = link_to "Get PDF to email", plan_pdf_path(@plan), class: "btn btn-primary", data: {confirm: "Are you sure?"}
#plan
  %section.lists-container
    - @plan.flow_steps.each do |fs|
      .list
        %h3.list-title= fs.title
        %ul.list-items
          - fs.tasks.each do |task|
            - if current_user.admin?
              = link_to edit_task_path(task) do
                %li= task.title
            -elsif current_user.level == task.level
              = link_to task_path(task) do
                %li= task.title
        -if current_user.admin?
          = form_for(:task, url: flow_step_tasks_path(flow_step_id: fs.id, plan_id: @plan.id), method: :post) do |f|
            %p
              = f.text_field(:title, {:class => 'form-control'})
            %p
              = f.submit("Add task", {:class => 'add-card-btn btn'})